project_id = "owsvuxxflhghlbrlhxst"

[functions.sync-guesty-data]
verify_jwt = false

[functions.sync-owners]
verify_jwt = false

[functions.sync-new-reservations]
verify_jwt = false

[functions.explode-reservation-nights]
verify_jwt = false

[functions.suggest-property-goals]
verify_jwt = true

[functions.forecast-revenue]
verify_jwt = true

[functions.generate-all-forecasts]
verify_jwt = false

[functions.generate-missing-forecasts]
verify_jwt = false

[functions.generate-bulk-goals]
verify_jwt = true
